#!/usr/bin/env ruby

require 'bagit'

input=ARGV
TargetBags = Array.new

def Create_manifest(input)
#Check and limit input
  if input.length > 1
    puts "Please only use one directory as input. Exiting."
    exit
  else
    input = input[0]
  end

  if ! File.directory?(input)
    puts "Input is not a valid directory. Exiting"
    exit
  end
  #Get list of directories
  Dir.chdir(input)
  bag_list = Dir.glob('*').select {|f| File.directory? f}
  #Check if directories are bags (contains metadata files)
  bag_list.each do |isbag|
    if ! File.exist?("#{isbag}/bag-info.txt") || ! File.exist?("#{isbag}/bagit.txt")
      puts "Warning! Unbagged directory found at -- #{isbag} Exiting"
    end
  end
  exit
  #Verify all bags are valid bags
  bag_list.each do |isvalidbag|
    bag = BagIt::Bag.new isvalidbag
    if bag.valid?
      TargetBags << isvalidbag
    else
      puts "Warning! Invalid Bag Detected! Dumping List of Validated Bags and Exiting!"

    end
  end
end


Create_manifest(input)